### PR TITLE
fix(extractPropName): use regexp to extract prop name

### LINKED ISSUE #81: Issue processing props
I ran into an interesting issue with the following code:

    <my-vue-comp v-prop-states="ctrl.states"></my-vue-comp>

When trying to load the app the console outputs the error:

```
logger.js:108 2019-03-07T22:40:23.908Z ERROR browser-console [Vue warn]: Missing 
required prop: "states"

found in

---> <Default1> at client/ui-components/MyVueComponent.vue
       <Root>
```

Stepping through the code I found that the reactive data object being passed to the vue instance constructor had a props property named `tates` instead of `states`. I finally noticed my typo that the prop in `v-prop-states` was singular and needed to be plural, but ngVue was parsing it as `vPropsTates`.

### PR DESCRIPTION
**Pull request by nicolaspayot**
Fixes #81

### CODE REVIEW

**Comment by dorayx** [comment]
could you add some tests?

**Comment by dorayx** [comment]
this pull request cannot be merged into master now
you need to create a branch from **v1.6.0** and push this pr to that branch
and so you can publish this fix **v1.6.1** for **v1.6** users
at the same time i think you should not publish **v1.7.0** until we merge this fix to **master** so that the bug will not affect the latest version **v1.7.0**

**Comment by nicolaspayot** [comment]
Oh right. This would have been better to publish v1.6.1 before, sorry. This fix is really an edge case though. I'll rebase with `master` then.

**Comment by nicolaspayot** [comment]
@dorayx what do you think?

**Comment by dorayx** [comment]
LGTM

**Pull request merged**
